import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import Footer from '@/components/global/Footer'
import Header from '@/components/global/Header'
import TanstackQueryProvider from '@/providers/tanstackQueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackQueryProvider>
          <div className="mx-auto flex min-h-screen max-w-7xl flex-col">
            <Header />
            <div className="grow">{children}</div>

            <Footer />
          </div>
        </TanstackQueryProvider>
      </body>
    </html>
  )
}
